project:
  type: website
  output-dir: docs
  resources: 
   - projects/business_strategy/business_strategy_consultancy_report.pdf
   - projects/business_strategy/business_strategy_presentation.pdf
   - projects/international_economy/international_economy.pdf
   - projects/portfolio_management/investment_portfolio.xlsx
   - projects/portfolio_management/investment_portfolio/investment_portfolio_presentation.html
   - assets/files/EU_economy_one.pdf
   - assets/files/EU_economy_two.pdf
   - assets/files/EU_economy_three.pdf
   - assets/files/EU_economy_four.pdf
   - projects/legal_system/criminal_law.pdf
   - assets/files/digital_transform_reflection.pdf
   - assets/files/jappers_report.pdf
   - assets/files/jappers_poster.pdf
   - assets/files/jappers_reflection.pdf
   - assets/files/lig1000_presentation.pdf
   - projects/digital_transformation/compare_contrast.pdf

website:
  title: "Martinas Jucys Brady"
  favicon: assets/mjb_favicon.png
  back-to-top-navigation: true
  navbar:
    title: false
    pinned: true
    logo: assets/mjb_favicon.png
    right:
      - href: projects.qmd
        icon: file-earmark-text
        text: Projects
      - href: about.qmd
        icon: person-circle        
        text: About
      - icon: github
        href: https://github.com/martinas-jucysbrady  
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/martinasjucysbrady/
        target: _blank
      - text: "**CV**"
        href: assets/CV.pdf
        target: _blank
      
  page-footer: 
    left: "© Martinas Jucys Brady, 2026"    
    right: "Built with [Quarto](https://quarto.org/)"


format:
  html:
    theme:
      - cosmo
    css: styles.css
    mainfont: sans-serif
    toc: false
    page-layout: full



