<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Martinas Jucys Brady">
<meta name="dcterms.date" content="2023-12-10">
<meta name="description" content="This Business Analytics case study analyses if physical bank branches boost checking account demand using MSA data, regression, and finds minimal impact after outlier removal.">

<title>Case Study: Business Analytics – Martinas Jucys Brady</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/mjb_favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-b21ff7c0af34b30ae757c621f1fb376d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/mjb_favicon.png" alt="" class="navbar-logo light-content">
    <img src="../../assets/mjb_favicon.png" alt="" class="navbar-logo dark-content">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> <i class="bi bi-file-earmark-text" role="img">
</i> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> <i class="bi bi-person-circle" role="img">
</i> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/martinas-jucysbrady" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/martinasjucysbrady/" target="_blank"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../assets/CV.pdf" target="_blank"> 
<span class="menu-text"><strong>CV</strong></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">1. Introduction</a></li>
  <li><a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis">2. Data Analysis</a>
  <ul class="collapse">
  <li><a href="#correlation-calculation" id="toc-correlation-calculation" class="nav-link" data-scroll-target="#correlation-calculation">2.1 <em>Correlation Calculation</em></a></li>
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression">2.2 <em>Simple Linear Regression</em></a></li>
  </ul></li>
  <li><a href="#risk-assessment" id="toc-risk-assessment" class="nav-link" data-scroll-target="#risk-assessment">3. Risk Assessment</a>
  <ul class="collapse">
  <li><a href="#financial-losses" id="toc-financial-losses" class="nav-link" data-scroll-target="#financial-losses"><em>3.1 Financial Losses</em></a></li>
  <li><a href="#customer-dissatisfaction" id="toc-customer-dissatisfaction" class="nav-link" data-scroll-target="#customer-dissatisfaction"><em>3.2 Customer Dissatisfaction</em></a></li>
  <li><a href="#competitors-gain-advantage" id="toc-competitors-gain-advantage" class="nav-link" data-scroll-target="#competitors-gain-advantage"><em>3.3 Competitors Gain Advantage</em></a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">4. Conclusion</a></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">5. Bibliography</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<div class="quarto-about-solana column-page-left">
  <div class="about-entity">
    <div class="entity-contents">
      <header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Case Study: Business Analytics</h1>
<p class="subtitle lead"><em>Is the presence of a physical bank branch creating demand for checking accounts</em></p>
  <div class="quarto-categories">
    <div class="quarto-category">Analytics</div>
    <div class="quarto-category">Year 2</div>
  </div>
  </div>
<div>
  <div class="description">
    This Business Analytics case study analyses if physical bank branches boost checking account demand using MSA data, regression, and finds minimal impact after outlier removal.
  </div>
</div>
<div class="quarto-title-meta column-page-left">
    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Martinas Jucys Brady </p>
          </div>
  </div>
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 10, 2023</p>
    </div>
  </div>
  </div>
</header> <div class="about-links">
  <a href="/projects/business_analytics/business_analytics.pdf" class="about-link" rel="" target="">
    <i class="bi bi-file-earmark-pdf"></i>
     <span class="about-link-text">Assignment PDF</span>
  </a>
</div>
      <div class="about-contents"><main class="content column-page-left" id="quarto-document-content">

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="business_analytics.jpg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Cover Page</figcaption>
</figure>
</div>
<hr>
<p>Hello Vice President Nils Bakker, I hope all is good with you. I have taken your question onboard and researched it appropriately to answer the question. Is the presence of a physical bank branch creating demand for checking accounts, was truly an intriguing question to answer, and I hope that my conclusion will aid you with sufficient data for the upcoming PAS meeting.</p>
<section id="introduction" class="level2">
<h2 data-anchor-id="introduction">1. Introduction</h2>
<p>To answer your query I used data from 120 Metropolitan Statistical Areas (MSAs), regarding household numbers in specific areas, the correlating figures for households within these areas that hold a checking account with our company and whether these areas have a physical bank branch within. Using this study I have been able to conclude whether there is a relationship between our physical bank branches and the demand for checking accounts with our company. By using various methodologies, assessments, and data visualisation to view the data gathered we have been able to gain strategical insights into consumer preferences and the effect of having physical banks.</p>
<p>My first step in answering your question was to prepare the data through careful analysis. I organised the data according to whether it the area in question had an inside footprint (with a physical bank branch) or an outside footprint (without a physical bank branch, but with ATMs instead). I then calculated the percentage of households with a checking account by the total number of households. I analysed the percentage values I got and carefully identified any outliers. To identify any outliers I used a scatterplot graph in order to be able to clearly distinguish any abnormalities. Below I have included an example of an outlier that I have identified.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="busana1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Figure 1: Identification of Outlier; Created by Martinas Jucys Brady</figcaption>
</figure>
</div>
<p>Here the household with the ID 114 is clearly seen as an outlier. I concluded that this was either due to the total number of households or households with a checking account being misinterpreted. The most logical reasoning for it to be an outlier is that instead of 10,731 total households, the real value should have been 107,310 total households, as then the percentage value would have been in line with the rest. Without any evidence I cannot change this value, so I proceeded to not include its values in my data.</p>
<p>Below I have included scatterplot representations of households with a checking account as a percentage of the total population, with any outliers removed.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="busana2.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Figure 2: Households with a Checking Account as % of Total Population (Outside); Created by Martinas Jucys Brady</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="busana3.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Figure 3: Households with a Checking Account as % of Total Population (Inside); Created by Martinas Jucys Brady</figcaption>
</figure>
</div>
</section>
<section id="data-analysis" class="level2">
<h2 data-anchor-id="data-analysis">2. Data Analysis</h2>
<section id="correlation-calculation" class="level3">
<h3 data-anchor-id="correlation-calculation">2.1 <em>Correlation Calculation</em></h3>
<p>Firstly I conducted a simple calculation to give me the average percentage of households with a checking account when there is a physical bank branch and when there isn’t one. The average percentage of households with a checking account when there is a bank branch is 1.42%. The average percentage of households with a checking account when there isn’t a checking account is 1.24%. These values indicate that there is a minimal difference in demand for a checking account whether or not the area has an inside or an outside footprint.</p>
<p>Also, the scatterplot below shows the linearity of the percentages of checking accounts from both inside and outside footprint. We can see that there is very little variability between values and that there are no distinct indicators to show that there is a difference in demand if there is a physical bank branch presence or not.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="busana4.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Figure 4: Scatterplot of Checking Account Demand; Created by Martinas Jucys Brady</figcaption>
</figure>
</div>
<p>To back this hypothesis, I will conduct multiple other studies.</p>
</section>
<section id="simple-linear-regression" class="level3">
<h3 data-anchor-id="simple-linear-regression">2.2 <em>Simple Linear Regression</em></h3>
<p>I used a simple linear regression model with the presence of a physical branch as the independent variable (indicated by using 0 for outside footprint and 1 for inside footprint) and the percentage of households with checking accounts as the dependent variable (in numerical format) in Excel. Using the in-built data analysis tool within Excel I was able to compare both sets of data. Below I have included the data that Excel provided me with.</p>
<div id="tbl-regression" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Regression results
</figcaption>
<div aria-describedby="tbl-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Coefficients</th>
<th>Std Error</th>
<th>t Stat</th>
<th>P-value</th>
<th>Lower 95%</th>
<th>Upper 95%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>0.30562</td>
<td>0.09675</td>
<td>3.15891</td>
<td>0.0025</td>
<td>0.14702</td>
<td>0.46412</td>
</tr>
<tr class="even">
<td>X</td>
<td>8.05829</td>
<td>6.11357</td>
<td>1.31806</td>
<td>0.1901</td>
<td>-4.0846</td>
<td>20.1651</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Here the Intercept X indicates the values for an outside footprint. The values of Variable 1 will be our main focus as these values indicates the differences between demand for checking accounts when there is a physical bank branch in the area compared to when there isn’t. From this data we are given 6 distinct values <span class="citation" data-cites="montgomery2021introduction">(<a href="#ref-montgomery2021introduction" role="doc-biblioref">Montgomery, Peck, and Vining 2021</a>)</span>.</p>
<ul>
<li><p>Coefficients represent the average change in the dependent variable in line with the change of the independent variable on the regression line. When Variable 1 changes from being an outside footprint to an inside footprint it sees an average increase of 8.059 units.</p></li>
<li><p>Standard error measures the variability of the data around the regression line. When the standard error value is low it indicates less variability from data within the dataset. Here this value is 6.113 and it indicates that there is large variability with the data.</p></li>
<li><p>The T-Stat value is the comparison between the coefficient and the standard error. When the t-value is higher this indicates that there is a larger influence when there is a change. From this data we can see that the t-value for Variable 1 is 1.318. This suggests that there is little significance in regard to the demand for a checking account if an area is with outside or inside footprint.</p></li>
<li><p>The P-values that are lower than a significance level of 0.05 indicate a strong relationship between the presence of a physical bank branch and an increased demand of checking accounts in an area. However, with the values given through this data it shows that the p-value 0.119 is higher than 0.05. This indicates that there is a poor relationship between a physical bank branch and the demand for a checking account.</p></li>
<li><p>Lower and Upper 95% confidence interval levels indicate where 95% of the population lies within the data.</p></li>
</ul>
<p>The data from this part of the linear regression model indicates that there is minimal significance of a physical bank branch on the demand for a checking account. Using more data from our Excel file, I was able to confirm this.</p>
<div id="tbl-reg-stats" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-reg-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Model summary statistics
</figcaption>
<div aria-describedby="tbl-reg-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Statistic</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Multiple R</td>
<td>0.120973</td>
</tr>
<tr class="even">
<td>R Square</td>
<td>0.014634</td>
</tr>
<tr class="odd">
<td>Adjusted R Square</td>
<td>0.006213</td>
</tr>
<tr class="even">
<td>Standard Error</td>
<td>0.49656</td>
</tr>
<tr class="odd">
<td>Observations</td>
<td>119</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>R square is an important value here as it indicates the percentage of values that have been influenced by the variable. Our variable here was if the area has an inside or outside footprint. The value, 0.014634, is low and shows that there was not much influence on the demand. This data has further strengthened my hypothesis.</p>
</section>
</section>
<section id="risk-assessment" class="level2">
<h2 data-anchor-id="risk-assessment">3. Risk Assessment</h2>
<p>Although my data is most likely correct, it may not represent the accurate effect it would have on the total population. Improper guidance can lead to major liquidity and efficiency for any business, so it is extremely important to conduct constant analyses and tests.</p>
<section id="financial-losses" class="level3">
<h3 data-anchor-id="financial-losses"><em>3.1 Financial Losses</em></h3>
<p>When we look at the process of risk assessment, the financial outcome is the most important aspect of all. Risks must be weighed in consideration to the correlation of expected income and expected risk, in order to make sure it is worth it. The data provided showed that physical branches have minimal effect on account demands, but this does not take into consideration the overall profits that can be made if a physical bank branch is established in a new area. For it to be worth establishing a new branch, the population of a specific area must be large enough for the company to gain sufficient profits from small percentage changes in account holders. If we were to establish a bank branch in an area with a low population, we may find that losses may be incurred. Considering this, risk assessments must take place for all scenarios to ensure that the company maximises profitability <span class="citation" data-cites="ramlall2018banking">(<a href="#ref-ramlall2018banking" role="doc-biblioref">Ramlall 2018</a>)</span>.</p>
</section>
<section id="customer-dissatisfaction" class="level3">
<h3 data-anchor-id="customer-dissatisfaction"><em>3.2 Customer Dissatisfaction</em></h3>
<p>Another effect of improper risk management can be the growth of customer dissatisfaction, due to consumer demands not being met. My analysis indicates that if there are no further physical bank branches established that there will be minimal increase in new customers, but it does not take the effect it will have on current customers. Just like the lady you had a conversation with on the plane, the establishment of branches in new areas may lead to increased customer loyalty and satisfaction. On the other hand, if we do not continue to grow our presence consumers may switch to more convenient banks with physical presences. When doing risk assessments we must take into consideration all possible positives and possible negatives, this includes consideration of increased interaction with current customers in an area. We may benefit or suffer greatly when taking this into consideration also.</p>
</section>
<section id="competitors-gain-advantage" class="level3">
<h3 data-anchor-id="competitors-gain-advantage"><em>3.3 Competitors Gain Advantage</em></h3>
<p>An easily neglected aspect of risk management regarding our dilemma may be that of the possible gain that can be made in the market share. Considering this, we must also consider the presence of other banks as this will have an effect on our possible gains and losses. Areas with a small physical bank branch presence may be of a higher interest as we can gain a higher market share within this area. On the other hand, in areas that are heavily congested with many competitors we may find it difficult to grow drastically due to the amount of competition. When considering establishing a physical bank branch we must not neglect this factor.</p>
<p>The following examples are those that depict the possible outcomes when risk assessment is conducted improperly. When risk assessments are done improperly it can lead to severe losses and even liquidation <span class="citation" data-cites="hull2012risk">(<a href="#ref-hull2012risk" role="doc-biblioref">Hull 2012</a>)</span>. In the past we have witnessed many banks enter liquidation or similar situations when risk assessment is not properly done. One such example is that of the Anglo-Irish Bank in 2008. This banks improper control of assets led to a terrible banking crisis in Ireland, as borrowing was not sufficiently controlled. “One of the costliest banking crisises in history” arose from the banks inability to accurately measure their capabilities in the department of borrowing and saving <span class="citation" data-cites="konzelmann2013banking">(<a href="#ref-konzelmann2013banking" role="doc-biblioref">Konzelmann and Fovargue-Davies 2013</a>)</span>. Anglo-Irish Bank were unable to give sustainable interest rates and suffered heavily, with losses financially and in customer satisfaction. This was due to the heavy reliance on international savings and borrowings that should have been analysed with more care.</p>
<p>The improper risk management of Citigroup between 1998 and 2009 proved to be catastrophic for its ability to remain functional. Citigroup employed an universal banking strategy that was designed to compete with those preexisting in the European and Asian markets, by using a high-risk high-reward concept. Excessive risk taking in Citigroup led to its collapse as it became unable to prevent legal violations and improper control of international borrowing <span class="citation" data-cites="wilmarth2014citigroup">(<a href="#ref-wilmarth2014citigroup" role="doc-biblioref">Wilmarth 2014</a>)</span>. Ultimately the risks taken did not reward, as it led to the Fed having to help them remain liquid for a large portion of time and the inability to pay out to its depositors.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 data-anchor-id="conclusion">4. Conclusion</h2>
<p>My initial hypothesis of establishing physical bank branches to not have an effect on the demand for checking accounts is highly likely to be accurate. We must also consider possible risks in specific MSAs that may be rewarding. I would suggest that a follow-up analysis of the possible gains that can be made through the establishment of physical bank branches in areas with an outside footprint be made. We would ultimately consider competitors, costs, effect on consumer interactions and the overall growth of market share in further studies so we can get an accurate interpretation of whether it is worth establishing these branches.</p>
<p>From the data that I have analysed here and before analysing deeper, I would suggest that no establishment of new bank branches be made, we must conduct much further research to ensure that establishing new branches would be viable. Currently I have concluded that the risk heavily outweighs the reward, as building and hiring staff for a new branch will be extremely costly and a failure could lead to many other knock-on effects. These knock-on effects can include the loss of current account holders and heavy financial losses.</p>
</section>
<section id="bibliography" class="level2">
<h2 data-anchor-id="bibliography">5. Bibliography</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-hull2012risk" class="csl-entry" role="listitem">
Hull, J. 2012. <em>Risk Management and Financial Institutions</em>. John Wiley &amp; Sons.
</div>
<div id="ref-konzelmann2013banking" class="csl-entry" role="listitem">
Konzelmann, S. J., and M. Fovargue-Davies. 2013. <em>Banking Systems in the Crisis: The Faces of Liberal Capitalism</em>. Routledge.
</div>
<div id="ref-montgomery2021introduction" class="csl-entry" role="listitem">
Montgomery, D. C., E. A. Peck, and G. G. Vining. 2021. <em>Introduction to Linear Regression Analysis</em>. John Wiley &amp; Sons.
</div>
<div id="ref-ramlall2018banking" class="csl-entry" role="listitem">
Ramlall, I. 2018. <em>The Banking Sector Under Financial Stability</em>. Bingley, United Kingdom: Emerald Publishing Limited. <a href="http://ebookcentral.proquest.com/lib/dcu/detail.action?docID=5608871">http://ebookcentral.proquest.com/lib/dcu/detail.action?docID=5608871</a>.
</div>
<div id="ref-wilmarth2014citigroup" class="csl-entry" role="listitem">
Wilmarth, A. E. Jr. 2014. <span>“Citigroup: A Case Study in Managerial and Regulatory Failures Symposium: Leading Academic, Business, and Government Figures Convene to Examine Law and the Financial Crisis.”</span> <em>Indiana Law Review</em> 47 (1): 69–138. <a href="https://heinonline.org/HOL/P?h=hein.journals/indilr47&amp;i=88">https://heinonline.org/HOL/P?h=hein.journals/indilr47&amp;i=88</a>.
</div>
</div>


</section>
<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main></div>
    </div>
  </div>
</div>
 <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/martinas-jucysbrady\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Martinas Jucys Brady, 2026</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>